version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    commands: 
    - wget -O jq https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
    - chmod +x ./jq
    - cp jq /usr/bin
    - jq --version 
  
         
  build:
    commands:
      - aws cloudformation package --template-file parentstack.yaml --s3-bucket rashmi-ohio-sam-demo --output-template-file packaged.yaml
      - aws s3 cp ./packaged.yaml s3://rashmi-ohio-sam-demo/packaged.yaml
      - aws s3 cp s3://rashmi-ohio-sam-demo/packaged.yaml /codebuild/output
      - echo $CODEBUILD_SRC_DIR
 

  post_build:
    commands:
      - ls 
      - chmod 777 test.sh
      - ./test.sh
artifacts:
  type: zip
  files:
    - packaged.yaml