AWSTemplateFormatVersion: 2010-09-09
Description: Redshift Stack 
Parameters:
  # VPCID:
  #   Type: String
  #   Type: AWS::EC2::VPC::Id
  #   Description: Select a VPC 
  DatabaseName:
    Type: String
    Description: Database name 
    Default: masterdb   
  MasterUsername:
    Type: String
    Description: Master user name for Redshift 
    Default: admin
  MasterUserPassword:
    Type: String
    Description: Master password for Redshift (used mixed case and numbers)
    NoEcho: true 
    Default: Admin$1234  
  
Resources:
  RedshiftCluster: 
    Type: AWS::Redshift::Cluster
    Properties: 
      ClusterSubnetGroupName: !Ref RedshiftClusterSubnetGroup
      ClusterType: multi-node  
      NumberOfNodes: 2
      DBName: !Sub ${DatabaseName}
      # IamRoles:
      #   - !GetAtt RawDataBucketAccessRole.Arn
      MasterUserPassword: !Ref MasterUserPassword
      MasterUsername: !Ref MasterUsername
      PubliclyAccessible: true
      NodeType: dc2.large
      Port: 5439
      VpcSecurityGroupIds: 
        # - !Sub ${RedshiftSecurityGroup}
        - sg-7c50361e
      PreferredMaintenanceWindow: Sun:09:15-Sun:09:45

  # RawDataBucketAccessRole:
  #   Type: AWS::IAM::Role
  #   Properties:
  #     AssumeRolePolicyDocument:
  #       Version: 2012-10-17
  #       Statement: 
  #         - 
  #           Effect: Allow
  #           Principal:
  #             Service:
  #               - redshift.amazonaws.com
  #           Action:
  #             - sts:AssumeRole
 
  RedshiftClusterSubnetGroup: 
    Type: AWS::Redshift::ClusterSubnetGroup
    Properties: 
      Description: Cluster subnet group
      SubnetIds: 
        - subnet-e20d168a
        - subnet-923a83de

Outputs:
  RedshiftClusterEndpointAddress:
    Description: Redshift Cluster Endpoint Address 
    Value: !GetAtt RedshiftCluster.Endpoint.Address 
  RedshiftClusterEndpoint:
    Description: Redshift Cluster Endpoint
    Value:       
      Fn::Join:
        - ""
        - - 'jdbc:redshift://'
          - !GetAtt RedshiftCluster.Endpoint.Address 
          - ':5439/'
          - !Sub ${DatabaseName}