pipeline {
    agent any
    parameters {
                credentials(name: 'CREDENTIALS', description: 'AWS Credentials', credentialType: 'Username with password')       
                string(name: 'Account_Name', description: 'Please Enter the name of the customer to be on boarded. (CustomerName-AssetName)')
                choice(name: 'Region', description: 'Please select the AWS Region', choices: 'eu-west-1\neu-west-2\neu-west-3\neu-central-1\nus-west-1\nus-west-2\nus-east-2\nus-east-1\nap-northeast-1\nap-northeast-2\nap-northeast-3\nap-south-1\nap-southeast-1\nap-southeast-2\nca-central-1\ncn-north-1\ncn-northwest-1\nsa-east-1')
                booleanParam(name: 'APPLY_CHANGES', defaultValue: false, description: 'If not opted, it will be dry run')
            }
    stages {
            stage ('Setup Env') {
                steps{
                    script {
                        currentBuild.displayName = "#${env.BUILD_NUMBER}-${env.ACCOUNT_NAME}-removeApp"
                        currentBuild.description = "${env.BUILD_NUMBER}-${env.ACCOUNT_NAME}-removeApp"
                    }
                }
            } 
            stage('Delete InitialSetup') {
                    steps {
                        withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: CREDENTIALS, secretKeyVariable: 'AWS_SECRET_ACCESS_KEY']]) 
                        {
                          sh (script: '''
                                #!bin/bash
                                aws cloudformation delete-stack --stack-name "InitialSetup-${Account_Name}"
                            ''')
                    
                    }
                }
            }
        }
}