variable "env_name" {}
variable "aws_access_key" {}
variable "aws_secret_key" {}
variable "aws_region" {}
variable "token" {}
variable "project_id" {}
variable "assets_expity_date" {}
variable "build_user" {}
variable "build_user_email" {}
