variable "aws_access_key" {}
variable "aws_secret_key" {}
variable "aws_region" {}
variable "token" {}
variable "hosted_zone" {}
variable "vpc_backend_bucket" {}
variable "vpc_backend_key" {}
variable "vpc_backend_region" {}
variable "project_id" {}
variable "assets_expity_date" {}
variable "build_user" {}
variable "build_user_email" {}
