AWSTemplateFormatVersion: "2010-09-09"
Description: "SNS Topics and Subscription"

Parameters:
    CustomerName:
      Type: String
      Description: Customer Name

    InfrastructureAdminEndpoint:
        Type: String
        Description: Email/Mailbox for Infrastructure Admin Alerts

    InfrastructureOpsEndpoint:
        Type: String
        Description: Email/Mailbox for Infrastructure Operations Alerts

    DbaEndpoint:
        Type: String
        Description: Email/Mailbox for Database (RDS) Alerts
Resources:
    InfrastructureAdmin: 
        Type: "AWS::SNS::Topic"
        Properties:
            DisplayName: !Sub ${CustomerName}_infrastructure_admin
            TopicName: !Sub ${CustomerName}_infrastructure_admin

    InfrastructureOps: 
        Type: "AWS::SNS::Topic"
        Properties:
            DisplayName: !Sub ${CustomerName}_infrastructure_ops
            TopicName: !Sub ${CustomerName}_infrastructure_ops

    Dba: 
        Type: "AWS::SNS::Topic"
        Properties:
            DisplayName: !Sub ${CustomerName}_dba
            TopicName: !Sub ${CustomerName}_dba

    InfrastructureAdminSubscription:
      Type: AWS::SNS::Subscription
      Properties:
          Endpoint: !Ref InfrastructureAdminEndpoint
          Protocol: email
          TopicArn: !Ref 'InfrastructureAdmin'

    InfrastructureOpsSubscription:
      Type: AWS::SNS::Subscription
      Properties:
          Endpoint: !Ref InfrastructureOpsEndpoint
          Protocol: email
          TopicArn: !Ref 'InfrastructureOps'

    DbaSubscription:
      Type: AWS::SNS::Subscription
      Properties:
          Endpoint: !Ref DbaEndpoint
          Protocol: email
          TopicArn: !Ref 'Dba'